### ISSUE TITLE
Issue na základě poznatků k první lekci PyLadies

### ISSUE THREAD

**Issue by zuzejk** [pyvec/naucse.python.cz#344]
Přidat do materiálů v místě konce instalace python to, jak si ihned ověřit, že instalace proběhla úspěšně (restart, command line -> python --	version). 

u instalace Pythonu (MacOS) je napsáno spusť v příkazové řádce příkaz, někdo nepochopil, že to znamená, že za tím příkazem má dát enter a také v případě MACu není v materiálech napsán mezikrok se zadáním hesla

přidala bych někam do triků s příkazovou řádkou používání šipky nahoru, dolů, tabulátoru, že se nedá používat ctrlV, ale dá se kopírovat a vložit přes pravé tlačítko

**Comment by encukou** [comment]
Už se to množí; měli bychom s tím na sprintu pohnout. Viz též:
* [ ] https://github.com/pyvec/naucse.python.cz/issues/313 Matoucí označení složky ~/pyladies
* [ ] https://github.com/pyvec/naucse.python.cz/issues/192 Lépe popsat kroky pro instalaci gitu na Windows
* [ ] https://github.com/pyvec/naucse.python.cz/issues/52 Tahák na základní příkazy přík. přádky
